---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: safe

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - ca-certificates
      - gnupg
      - fontconfig
      - lsb-release
      - software-properties-common
      - apt-transport-https
      - unzip
    state: present

- name: Ensure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
